openapi: 3.0.0
info:
  title: DNA
  version: 1.0.0
servers:
  # - url: http://localhost:3001
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: users
  - name: groups
paths:
  /api/groups/v1/permissions/:id:
    put:
      tags:
        - groups
      summary: groups/v1/permissions/:id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                limit: 10
                offset: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/groups/v1/getall:
    post:
      tags:
        - groups
      summary: groups/v1/getall
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                limit: 10
                offset: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/users/v1/getall:
    get:
      tags:
        - users
      summary: users/v1/getall
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/users/v1/login:
    post:
      tags:
        - users
      summary: property/v1/login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: test@m.com
                password: d1n!4321

      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /:
    get:
      tags:
        - default
      summary: test
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

            
